name: Aurioncolortablist
version: ${version}
main: com.mineaurion.aurioncolortablist.Aurioncolortablist
authors: [Yann151924]
description: Color Tablist based on luckperms
website: https://mineaurion.com
depend: [LuckPerms]
commands:
  aurioncolortablist:
    aliases: [act]
    description: "Aurion Color Tablist Command"
permissions:
  aurioncolortablist.admin:
    default: false
    description: "Aurion Color Tablist Admin"