sudo: false
language: java
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
    - "spigot/build/libs/*"
    - "sponge/build/libs/*"
  skip_cleanup: true
  on:
   repo: Mineaurion/AurionColorTablist
   tags: true